services:
  db:
    image: postgres:15
    container_name: sleep_db_container
    restart: always
    env_file:
      - ./db/.env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data: